### ISSUE TITLE
Price FROM - TO

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#5336] opened 2023-03-23 12:28 UTC
### What happened?

 Go to explore: Items: Filter: After setting the price FROM 1 - 2: 

1. It would be good to add **KSM** there so we know its price in KSM not USD/EUR of something else
2. I cannot see my filter anywhere - This screenshot is after setting the price from 1-2. What should I do in case I want to cancel the search by price from 1-2? Good would be to add it next to the buy now filter.

<img width="1433" alt="Screenshot 2023-03-23 at 13 17 59" src="https://user-images.githubusercontent.com/104380776/227203551-a5eaa440-0fb0-43e8-bec5-1c2e25791979.png">

### Please reproduce in steps

Explore - Items - set price from 1 to 2. 

### Expected Behavior

see the price filter

### What browsers are you seeing the problem on?

Chrome

### At which address did you encounter bug?

beta.kodadot.xyz

### Are you logged in?

Yes

### Which wallet you are using?

PolkadotJS

### Screenshots

-

### Payment link for reward

https://kodadot.xyz/transfer/?target=%3CMy_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address%3E

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by exezbcz** [comment] 2023-03-23 12:54
duplicate of
- #5167 

its not working anywhere yet

**Closed** 2023-03-24 13:12 UTC
Labels: bug, rmrk
