### ISSUE TITLE
Search: Something not working

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#7735] opened 2023-10-18 15:54 UTC
I tried to search this NFT: https://kodadot.xyz/ahp/gallery/5-1 (name of the NFT: Rorty)
Chain: AHP

<img width="1882" alt="Screenshot 2023-10-18 at 17 53 26" src="https://github.com/kodadot/ops-internal/assets/104380776/c8f04220-feee-4c93-be5b-f612448fda09">

Results
---

I clicked enter and these are results. A lot of NFTs ......

<img width="1878" alt="Screenshot 2023-10-18 at 17 51 57" src="https://github.com/kodadot/nft-gallery/assets/104380776/6581d687-c23e-41c5-b78d-a032e2e50c8f">

1547 Items (NFTs) that appeared after searching for Rorty NFT on Asset Hub Polkadot. Definitely, something is not working because those NFTs don't have "Rorty" in their names, description,s properties"

**Comment by daiagi** [comment] 2023-10-19 06:45
duplicate of 
* #7705

**Comment by daiagi** [comment] 2023-10-19 07:24
fixed by #7710 !

[image](https://github.com/kodadot/nft-gallery/assets/22791238/484a4430-37fe-41f1-b013-8b37d453a2c3)

**Closed by daiagi** 2023-10-19 07:24 UTC
Labels: bug, p2, A-statemint-ahp
