### ISSUE TITLE
Migrate app from Vue 2 to Vue 3.

### ISSUE THREAD

**Issue by zhyd1997** [kodadot/nft-gallery#5716] opened 2023-04-18 12:47 UTC
### Is your feature request related to a problem?

Unlock Vite, Nuxt 3 and [Nuxt i18n](https://v8.i18n.nuxtjs.org/) (compatible with vue i18n) for better DX and UX:
<img width="374" alt="Screenshot 2023-04-18 at 20 25 20" src="https://user-images.githubusercontent.com/31362988/232776553-7308f2cd-9e6d-419d-89a0-e2cc826ce216.png">

### Describe the solution you would like

Currently 50.1 % of files in [codebase](https://github.com/kodadot/nft-gallery/search?l=vue) (based on this [commit](https://github.com/kodadot/nft-gallery/commit/b8d9b40eeabbbeeb453a163ca34e34fa7baca048)) written in Vue (2):
<img width="331" alt="Screenshot 2023-04-18 at 20 32 06" src="https://user-images.githubusercontent.com/31362988/232778079-1a4f437d-95bf-4aef-84a1-0e4c1aa1747d.png">

and distributed in these folders:

- [ ] `components`
- [ ] `layouts`
- [ ] `libs/ui/src/components`
- [ ] `pages`

the solution is we can start from scratch which only install need libraries used in portal file, and then add more pages which will be writen in Vue 3.

the initial files can be setup by `pnpm dlx nuxi init <project-name>`.

### Describe alternatives you have considered

Or start from Vue 3 directly:

<img width="751" alt="Screenshot 2023-04-18 at 20 42 14" src="https://user-images.githubusercontent.com/31362988/232780653-867c3ec8-9f47-421c-8826-9d40c7f56d47.png">

> the libraries seems that is needed in current codebase.

and then option in Nuxt 3.

### Are there opened related issues?

[Towards Vue 3 / Nuxt 3](https://github.com/kodadot/nft-gallery/issues/2690#top)

**Comment by roiLeo** [comment] 2023-04-18 12:57
> ### Describe the solution you would like
> 
> Currently 50.1 % of files in [codebase](https://github.com/kodadot/nft-gallery/search?l=vue) (based on this [commit](https://github.com/kodadot/nft-gallery/commit/b8d9b40eeabbbeeb453a163ca34e34fa7baca048)) written in Vue (2): <img alt="Screenshot 2023-04-18 at 20 32 06" width="331" src="https://user-images.githubusercontent.com/31362988/232778079-1a4f437d-95bf-4aef-84a1-0e4c1aa1747d.png">

should be done with #4750 

> the solution is we can start from scratch which only install need libraries used in portal file, and then add more pages which will be writen in Vue 3.

Hmm.. good luck with that

> the initial files can be setup by `pnpm dlx nuxi init <project-name>`.
> ### Describe alternatives you have considered
> 
> Or start from Vue 3 directly:

I would keep nuxt for SSR.

> ### Are there opened related issues?

Duplicate of #2690?

**Comment by yangwao** [comment] 2023-04-19 12:42
hey @zhyd1997 if you want to be dedicated to this it would be more than welcome to unlock for us Vue3, Vite and a lot of recent perks. 

Happy to pay you some gig if you manage crack on this, would you be up to?

Yet if so, I would like to see this hard work in a separate branch like `vue3` as you'll have a lot of conflicts at our current pace of amount of PRs. I can set a dedicated deployment branch for you if you say yes.

**Comment by zhyd1997** [comment] 2023-04-19 13:49
Thanks but I am not familiar with Vue, just my idea, can share on Twitter to see if someone is interesting in it.

**Comment by yangwao** [comment] 2023-04-25 11:55
> just my idea, can share on Twitter to see if someone is interesting in it.

Hey, yes sure, that would help us a lot! 
If someone want to work on it, there is still existing progress for this. 
Feel free to help and get rewarded helping us out on this!

- #2690

**Closed by yangwao** 2023-04-25 11:55 UTC
Labels: enhancement
