### ISSUE TITLE
husky: Permission denied

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#3539] opened 2022-07-22 16:50 UTC
Seems these two PRs doesn't builds

https://github.com/kodadot/nft-gallery/pull/3538
https://github.com/kodadot/nft-gallery/runs/7471270458?check_suite_focus=true

```
> kodadot-nft-gallery@3.0.0 prepare /home/runner/work/nft-gallery/nft-gallery
> husky install
sh: 1: husky: Permission denied
 ELIFECYCLE  Command failed with exit code 126.
Error: Process completed with exit code 1.
```

**Comment by prachi00** [comment] 2022-07-22 16:52
https://stackoverflow.com/questions/51811564/sh-1-node-permission-denied
seems like some issue with broken packages?

**Comment by preschian** [comment] 2022-07-23 04:25
should be fixed by this https://github.com/kodadot/nft-gallery/pull/3536
root cause: https://github.com/kodadot/nft-gallery/pull/3530#issuecomment-1192661314

**Closed** 2022-07-23 08:00 UTC
Labels: bug, $, p1
