### ISSUE TITLE
Enough: Quality and resolution is very bad

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#10347] opened 2024-05-27 08:56 UTC
Collection [Enough](https://kodadot.xyz/ahp/gallery/130-2405249231).

Tried to open full-screen mode:
1) Images are in very low resolution?! 
2) once downloaded, they look like this:

![2024-05-27 10 51 59](https://github.com/kodadot/nft-gallery/assets/104380776/7d257a6b-064e-49d1-b8c1-17f3a85f9cbf)
![2024-05-27 10 51 55](https://github.com/kodadot/nft-gallery/assets/104380776/e7701210-cb16-4b53-b240-f1366cc6114e)

I have an info that the original code should make images with higher resolution - in a much better quality

**Comment by ThomasssArt** [comment] 2024-05-27 09:26
The problem is that if you choose the "open in new tab" feature (for #12 and #13) it points to the wrong directory (not to the IPFS directory):

Working example:
https://image.w.kodadot.xyz/ipfs/bafybeihgo4a44is6iieu5d2ufb5ni53myeyek464ueapkubrcbyvt54hxi/?hash=0x57d84098fabaa9d891995ae78ef5bd0c228ba73d91e7470b4e2b0d0485f41e61

Not working example:
https://fxart-beta.kodadot.workers.dev/metadata/v2/image?chain=ahp&collection=130&hash=0x2197f1774c2843dd87bb3f99ec89a7b8c0fc76980f6df71ca347c2d88c030c52

Fixed example:
https://image.w.kodadot.xyz/ipfs/bafybeihgo4a44is6iieu5d2ufb5ni53myeyek464ueapkubrcbyvt54hxi/?hash=0x2197f1774c2843dd87bb3f99ec89a7b8c0fc76980f6df71ca347c2d88c030c52

**Comment by vikiival** [comment] 2024-05-27 09:42
Hey, so the point of the issue is that @preschian changed the resolution settings to 300x300 px, and no one was aware of it. 

Pres said he will fix it,
thanks for the reporting.

> not to the IPFS directory

@ThomasssArt we have a special route that stores the image previews, however the art itself is always stored on IPFS

**Comment by ThomasssArt** [comment] 2024-05-27 10:59
> > not to the IPFS directory
> 
> @ThomasssArt we have a special route that stores the image previews, however the art itself is always stored on IPFS

@vikiival yeah thats what i meant. Image previews (thumbnails) are stored somewhere and the art itself gets stored on IPFS. 

After you choose "open in new tab" it just rooted to the thumbnail and not to the IPFS.

**Comment by preschian** [comment] 2024-05-27 11:16
> After you choose "open in new tab" it just rooted to the thumbnail and not to the IPFS.

This is the problem, and it should be fixed here: https://github.com/kodadot/nft-gallery/pull/10349. That was because missing this line: https://github.com/kodadot/nft-gallery/pull/9927/files#diff-5937c7434b4c50a2f0bfa46e13f06ccb54f226bf0820f7ab958781d1b0d44b02L82-L95

**Comment by ThomasssArt** [comment] 2024-05-28 13:44
New mints same problem... What is wrong there? Do we really need to check this for every new mint???????

#15 --> everything is fine:
https://image.w.kodadot.xyz/ipfs/bafybeihgo4a44is6iieu5d2ufb5ni53myeyek464ueapkubrcbyvt54hxi/?hash=0xb7c52b3a0eb139fae280e892c8fa20ae64b7a859af915b12b6dd5a103076d1ac

#14 --> same old issue
https://fxart-beta.kodadot.workers.dev/metadata/v2/image?chain=ahp&collection=130&hash=0x07f3bbee25109f56a0fb7aaa0e65cc8458067db16f7791e60fbdbf8ac8c83bd3

**Comment by preschian** [comment] 2024-05-28 14:04
> and it should be fixed here: https://github.com/kodadot/nft-gallery/pull/10349

@ThomasssArt Currently, the pull request is being reviewed. You can check in the link above. Previous and future drops will be fixed in that PR. Once the review is done, it needs to be deployed to production. Meanwhile, you can check that deployment preview in this link: [deploy-preview-10349--koda-canary.netlify.app](https://deploy-preview-10349--koda-canary.netlify.app/ahp/gallery/130-2405249231)

**Closed** 2024-05-30 12:18 UTC
Labels: bug, p1, A-generative
