### ISSUE TITLE
Reporting Bug/ Error

### ISSUE THREAD

**Issue by nine73** [kodadot/nft-gallery#10589] opened 2024-07-05 16:03 UTC
### Is there an existing issue?

- [X] I have searched the existing issues

### What happened?

Uploading/Creating new NFT, and keep getting this error...

Warning
Error: [NFT::STORAGE] Unable to PIN File for reasons HTTP status server error (503 Service Unavailable) for url (https://api.nft.storage/upload)

### Please reproduce in steps

Uploading/Creating new NFT, and keep getting this error...

Warning
Error: [NFT::STORAGE] Unable to PIN File for reasons HTTP status server error (503 Service Unavailable) for url (https://api.nft.storage/upload)

### Expected Behavior

Uploading/Creating new NFT, and keep getting this error...

Warning
Error: [NFT::STORAGE] Unable to PIN File for reasons HTTP status server error (503 Service Unavailable) for url (https://api.nft.storage/upload)

### What browsers are you seeing the problem on?

Desktop Chrome

### At which address did you encounter bug?

kodadot.xyz

### Are you logged in?

Yes

### Which wallet you are using?

Talisman

### At which chain did you encounter bug?

Asset Hub Polkadot

### Screenshots

<img width="1728" alt="Screen Shot 2024-07-05 at 11 59 38 AM" src="https://github.com/kodadot/nft-gallery/assets/39445390/9ed63c49-6e28-49cf-8640-a515479d6388">

### Wallet Address & Transaction hash

16iaMiYDty42YDzuPdpvWBA6YDXeZ7eXhbi5ba2dowNWvDE9

### Relevant log output

```shell
Warning
Error: [NFT::STORAGE] Unable to PIN File for reasons HTTP status server error (503 Service Unavailable) for url (https://api.nft.storage/upload)
```

### Payment link for reward

https://canary.kodadot.xyz/dot/transfer/?target=<My_Polkadot_Address_check_https://github.com/kodadot/nft-gallery/blob/main/REWARDS.md#creating-your-dot-address>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vikiival** [comment] 2024-07-08 09:23
Duplicate of #10588

**Closed by vikiival** 2024-07-08 09:23 UTC
Labels: bug
