### ISSUE TITLE
Waifu mint progress bug

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#6269] opened 2023-06-18 13:25 UTC
![image](https://github.com/kodadot/nft-gallery/assets/90852205/adb4ea13-a273-4927-8970-b1c142a204c3)
- should be black typeface

**Comment by roiLeo** [comment] 2023-06-20 08:58
related with #6254 something wrong with oruga config

**canary**
<img width="403" alt="Capture d’écran 2023-06-20 à 10 54 17 AM" src="https://github.com/kodadot/nft-gallery/assets/9987732/ec7e1f78-0c1e-4021-9d7f-34382a20846a">

**kodadot.xyz**
<img width="412" alt="Capture d’écran 2023-06-20 à 10 57 10 AM" src="https://github.com/kodadot/nft-gallery/assets/9987732/a36afa7a-17ef-42c1-84e8-bfb2b1e75342">

code is duplicated and the one taking in count on canary is the one from https://github.com/kodadot/nft-gallery/blob/ce5ab4054216fffab38926cceea3fc8385aca562/styles/index.scss#L11

@preschian any idea what happened?

**Comment by preschian** [comment] 2023-06-20 09:16
> code is duplicated and the one taking in count on canary is the one from

interesting, seems like an ordering problem?

it reminds me of the issue on the next.js side 🤔
https://github.com/vercel/next.js/issues/16630

**Comment by preschian** [comment] 2023-06-20 09:25
@roiLeo wanna try to remove this line? `@import "~@oruga-ui/oruga/src/scss/oruga";`

**Comment by preschian** [comment] 2023-06-20 09:26
nvm, it broke elsewhere

**Comment by roiLeo** [comment] 2023-06-20 09:26
> @roiLeo wanna try to remove this line? `@import "~@oruga-ui/oruga/src/scss/oruga";`

Yes It worked on my side but If we remove this line we will have side effects from oruga components which are not based on `libs/ui`

**Comment by preschian** [comment] 2023-06-20 09:31
```css
// OVERRIDE ORUGA COMPONENTS
@import "components/o-table";
@import "components/o-tabs";
@import "components/o-tooltip";
```

seems like only `o-tabs` are left. once this PR merged https://github.com/kodadot/nft-gallery/pull/6231 let's try removing all of them on `index.scss`

**Comment by preschian** [comment] 2023-06-20 09:32
> we will have side effects from oruga components which are not based on `libs/ui`

oh correct, I forgot that we still directly import from oruga. for example, `OCarousel`

**Comment by roiLeo** [comment] 2023-06-20 09:38
Idk why but it work on kodadot.xyz while there are no major changes (#6291)

**Comment by preschian** [comment] 2023-06-21 06:38
> Idk why but it work on kodadot.xyz while there are no major changes (#6291)

@roiLeo I found a weird hint. fixed when I change it to `b-button` on this line https://github.com/kodadot/nft-gallery/blob/main/layouts/error.vue#L19

**Comment by roiLeo** [comment] 2023-06-21 06:46
> > Idk why but it work on kodadot.xyz while there are no major changes (#6291)
> 
> @roiLeo I found a weird hint. fixed when I change it to `b-button` on this line
> 
> https://github.com/kodadot/nft-gallery/blob/053f8b86ab3049def9b7f3bba27158674749012a/layouts/error.vue#L19

Lol wtf, it's working!

Code is still duplicated but now the one taken first is the one from `libs/ui`.
This is a weird bug, any idead what's happening? Maybe since we import `NeoButton` in error layout which is imported in every template?

**Comment by preschian** [comment] 2023-06-21 07:21
> Code is still duplicated but now the one taken first is the one from `libs/ui`.

I guess this is an ordering issue instead of duplicated stuff

| broken | correct |
|--------|--------|
| ![image](https://github.com/kodadot/nft-gallery/assets/734428/a5401eca-cc91-42e1-a5b2-e0d05e6f50f8) | ![image](https://github.com/kodadot/nft-gallery/assets/734428/edefe7cf-c6ee-4b4a-9573-dcfabd13eafe) | 



> This is a weird bug, any idead what's happening?

no idea why. not sure what is the correlation between them. if we couldn't find the root cause, I think we cant rely on the scss variable to change the oruga property. for example, 

use this:
```css
.o-steps {
  .o-steps__title {
    background-color: hsla(0, 0%, 0%, 0);
  }
}
```

instead of:
```css
$steps-details-background-color: hsla(0, 0%, 0%, 0);
```

**Comment by preschian** [comment] 2023-06-21 07:24
or, better let's remove this line `@import "~@oruga-ui/oruga/src/scss/oruga";`

need to migrate this first:
- OCarousel
- OUpload

**Comment by roiLeo** [comment] 2023-06-21 07:32
> or, better let's remove this line `@import "~@oruga-ui/oruga/src/scss/oruga";`

Yes this is duplicated code issue, it will be removed once migration completed.

But for order issue works well on #6298,

> use this:
> 
> ```css
> .o-steps {
>   .o-steps__title {
>     background-color: hsla(0, 0%, 0%, 0);
>   }
> }
> ```
> 
> instead of:
> 
> ```css
> $steps-details-background-color: hsla(0, 0%, 0%, 0);
> ```

 do you think this would be a better solution?

**Comment by preschian** [comment] 2023-06-21 07:50
> do you think this would be a better solution?
> it will be removed once migration completed

migration is better I guess

**Closed** 2023-06-21 11:34 UTC
Labels: p3, visual change, A-ai-minter, E-easy
