### ISSUE TITLE
Buying NFTs not working? 

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#5780] opened 2023-04-24 09:54 UTC
### What happened?

I tried to buy [this NFT](https://kodadot.xyz/rmrk/gallery/15340420-7E5F11C88BA4139716-SNEK-PSYCHEDELIC_SNAKE-0000000000000001) but it got stuck like this:
<img width="1436" alt="Screenshot 2023-04-24 at 11 50 04" src="https://user-images.githubusercontent.com/104380776/233962662-9e889114-c72c-43a2-a6f2-7406dc934cde.png">

Tried different wallet but still:
<img width="1418" alt="Screenshot 2023-04-24 at 11 51 54" src="https://user-images.githubusercontent.com/104380776/233962891-84e912d6-bd80-4ecb-8e2c-cffd244ccf9a.png">

Tried on beta with different NFTs but then I only got this:
<img width="617" alt="Screenshot 2023-04-24 at 11 52 38" src="https://user-images.githubusercontent.com/104380776/233963229-c3b5ca3e-3193-4eb3-9bef-6d7536be0872.png">

### Please reproduce in steps

Buy NFT

### Expected Behavior

buy it

### What browsers are you seeing the problem on?

Desktop Chrome

### At which address did you encounter bug?

beta.kodadot.xyz, kodadot.xyz

### Are you logged in?

Yes

### Which wallet you are using?

PolkadotJS

### At which chain did you encounter bug?

Kusama

### Screenshots

- 

### Payment link for reward

https://kodadot.xyz/transfer/?target=%3CMy_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address%3E

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JustLuuuu** [comment] 2023-04-24 10:02
Update: its working on canary.

**Comment by JustLuuuu** [comment] 2023-04-24 10:08
Surprisingly after buying one NFT on canary, its possible to buy also in production... not sure why this issue appeared tho

**Comment by vikiival** [comment] 2023-04-24 10:17
Duplicate of: 
- https://github.com/kodadot/nft-gallery/issues/5319
- https://github.com/kodadot/nft-gallery/issues/5316

If you stuck on 1/3 it means that the blockchain node is not producing blocks.
It happened on prod because you may have been connected to the **dwelir** which was removed in - #5690


The error you see is telling you that you made same transactions

<img width="617" alt="233963229-c3b5ca3e-3193-4eb3-9bef-6d7536be0872-2" src="https://user-images.githubusercontent.com/22471030/233968518-c8ecac47-9892-4701-b0d1-cd7c650fc5e3.png">

**Comment by yangwao** [comment] 2023-04-24 12:56
Actually this should not happen on nor chains 👀 

Anyway smol refreshment coming to production
- #5791

**Comment by JustLuuuu** [comment] 2023-04-24 14:45
Same with minting. the artist is sad.
![2023-04-24 16 43 14](https://user-images.githubusercontent.com/104380776/234031894-f16dc6c9-1fde-4eff-b20a-50f88c997bd4.jpg)

**Comment by vikiival** [comment] 2023-04-24 14:50
Please use beta, maybe there is some chache that is holdinh the artist

**Comment by yangwao** [comment] 2023-04-25 08:15
iirc if it's submitted and rpc node pushes it to the network it should pass, but sometimes it drops mempool. 

We've mitigated it to remove the node which was doing this (dwellir) but sometimes it can happen to any node and it's out of our control until we want to run our own rpc endpoint (which we will eventually probably)

**Comment by yangwao** [comment] 2023-04-25 08:15
Solution could be to use Substrate connect best (?) in our code yet it's experimental

**Comment by JustLuuuu** [comment] 2023-04-25 11:01
<img width="456" alt="Screenshot 2023-04-25 at 13 01 01" src="https://user-images.githubusercontent.com/104380776/234257351-c6fa3f84-4b5a-4686-8892-c8c61eb1dfe2.png">

**Comment by JustLuuuu** [comment] 2023-04-26 08:20
> Hey Linda, it's me again, can he give try out beta to mitigate some cache issues? But albeit, both should be on same version iirc as this fix was sent down the road already.

he was already trying it there. will tell him to try again

> 
> Also, can he give us screenshot from console? Especially red lines there and context
> 
> On OSX - option + cmd + j On Windows - ctrl + shift + j
> 
> Also let's bump this one in queue then

![2023-04-26 10 14 40](https://user-images.githubusercontent.com/104380776/234514330-d540b739-66f2-45f7-b2af-c06a341259a1.jpg)
![2023-04-26 10 14 46](https://user-images.githubusercontent.com/104380776/234514358-6adf40e4-5faa-444c-b742-7d5560f43620.jpg)

**Comment by vikiival** [comment] 2023-04-26 09:13
2 things:
- artist is still connected to dwelir

**Comment by JustLuuuu** [comment] 2023-04-27 06:36
> 2 things:
> 
> * artist is still connected to dwelir

Thats one thing. 😄 How can people using our platform change that?

<img width="1454" alt="Screenshot 2023-04-27 at 08 30 30" src="https://user-images.githubusercontent.com/104380776/234778804-cb3f950a-9860-477d-96d6-92f6bbd533f0.png">

This thing in settings does nothing because after refreshing we are back in dwelir. 

A message from a different artist from yesterday evening:

<img width="644" alt="Screenshot 2023-04-27 at 08 27 24" src="https://user-images.githubusercontent.com/104380776/234778061-30bec207-9352-41d4-b584-a49d825ad9b2.png">

Idk what to tell them. So KodaDot in production is not working because of that - you cannot buy, mint, burn.. When can we expect a new release from beta that will solve this?

**Comment by yangwao** [comment] 2023-08-04 19:15
Still thing?

**Comment by vikiival** [comment] 2023-08-04 21:10
Doubt, no longer use dwelir, switched to more reliable nodes.

**Closed by vikiival** 2023-08-04 21:10 UTC
Labels: p1, 🧙‍♀️ - bug-hunt, A-rmrk
