### ISSUE TITLE
failed listing transaction 

### ISSUE THREAD

**Issue by Pavel333333** [kodadot/nft-gallery#3487] opened 2022-07-19 20:56 UTC
### Is your feature request related to a problem?

I put a Price of 3 bsx and a balance of 10000 and the transaction ended with an error. but as a user, I don't understand how to solve this error.

### Describe the solution you would like

it is necessary to explain in detail and accessible to everyone why the transaction failed and what needs to be done to make it successful

### Describe alternatives you have considered

I had to create a new NFT.

### Screeenshots

![kodadot_2](https://user-images.githubusercontent.com/88947332/179846765-9fc210f0-8f6d-4808-b3d8-2248d7331ad1.png)

**Comment by petersopko** [comment] 2022-07-20 12:18
I've tried this couple times, can't reproduce, pretty weird error tbh, seems that the owner has changed in the mean time? or the wallet changed? can you provide link to the NFT?

**Comment by Pavel333333** [comment] 2022-07-20 12:38
I did two nfts . one of them tried to burn, but the transaction ended unsuccessfully. and now I can't find this nft in my profile. that is, I can't find the tae that I wanted listing, but I couldn't send it to listing and I decided to delete it, then make a new tae and send it to listing. in general, everything is very difficult on the platform. it's hard to figure out. 20.07.2022, 15:18, "Peter Sopko" ***@***.***>: I've tried this couple times, can't reproduce, pretty weird error tbh, seems that the owner has changed in the mean time? or the wallet changed? can you provide link to the NFT?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by petersopko** [comment] 2022-07-21 09:33
I'd gladly try to figure out some fix for this one, but I cannot seem to reproduce it. Possibly connected to:
- #3364 

and perhaps being fixed in:
- https://github.com/kodadot/nft-gallery/pull/3500

if you run into this error again, please let us know and it would be best if you could provide screenshot from console :) @Pavel333333

**Closed by petersopko** 2022-07-21 09:33 UTC
Labels: enhancement

**Comment by Pavel333333** [comment] 2022-07-21 10:15
yes, this bug has been fixed 21.07.2022, 12:33, "Peter Sopko" ***@***.***>: I'd gladly try to figure out some fix for this one, but I cannot seem to reproduce it. Possibly connected to:#3364and perhaps being fixed in:#3500if you run into this error again, please let us know and it would be best if you could provide screenshot from console :) @Pavel333333—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
