### ISSUE TITLE
Show BSX in offer dialog at item 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#3234] opened 2022-06-21 14:57 UTC
When I'm making offer, it shows in KSM? 

<img width="355" alt="image" src="https://user-images.githubusercontent.com/5887929/174831215-55c2dddb-2321-4fbf-a54f-0964e9f7aa5e.png">

**Comment by petersopko** [comment] 2022-06-21 15:14
same thing on rmrk, happens when wallet gets stuck during switching between chains
![image](https://user-images.githubusercontent.com/73316633/174833662-1845f8fd-0160-4d15-b863-be616248c4b0.png)

linked to
- https://github.com/kodadot/nft-gallery/issues/3197

**Comment by roiLeo** [comment] 2022-06-27 09:35
![Screenshot 2022-06-27 at 11-34-14 KodaDot - Kusama NFT Market Explorer](https://user-images.githubusercontent.com/9987732/175908866-1f191afc-66a7-4bfa-8762-da0a087ebf84.png)

can't reproduce might be closed by #3252

**Comment by petersopko** [comment] 2022-06-27 11:57
> can't reproduce might be closed by #3252

yes, closed in there

**Closed by petersopko** 2022-06-27 11:57 UTC
Labels: $, p2, 🐍 - basilisk, item
