### ISSUE TITLE
value "10000000000000000000000" is out of range for type bigint

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#5292] opened 2023-03-17 12:57 UTC
@ beta

![image](https://user-images.githubusercontent.com/5887929/225910417-061b531e-79e2-4fbb-94e4-b20f8cfac5df.png)

![image](https://user-images.githubusercontent.com/5887929/225910441-8c5f6b53-e470-4197-91a7-d9d1738f3ad9.png)

coming from rubick

`https://squid.subsquid.io/rubick/v/009-rc0/graphql`

```json
{
    "errors": [
        {
            "message": "value \"10000000000000000000000\" is out of range for type bigint",
            "locations": [
                {
                    "line": 2,
                    "column": 3
                }
            ],
            "path": [
                "events"
            ],
            "extensions": {
                "code": "INTERNAL_SERVER_ERROR",
                "exception": {
                    "query": "SELECT\n    DISTINCT ne.id as id,\n    ne.name as name,\n    ne.issuer as issuer,\n    ne.metadata as metadata,\n    e.current_owner,\n    me.image as image,\n    me.animation_url,\n    MAX(e.timestamp) as timestamp,\n    MAX(e.meta::bigint) as value,\n    ne.collection_id as collection_id,\n    ce.name as collection_name\n\nFROM event e\n    JOIN nft_entity ne on e.nft_id = ne.id\n    LEFT join metadata_entity me on me.id = ne.metadata\n    LEFT JOIN collection_entity ce on ne.collection_id = ce.id\nWHERE\n    e.interaction = $1\n    AND ne.burned = false\n    \nGROUP BY ne.id, me.id, e.current_owner, me.image, ce.name\nORDER BY MAX(e.timestamp) DESC\nLIMIT $2 OFFSET $3",
                    "parameters": [
                        "LIST",
                        30,
                        0
                    ],
                    "driverError": {
                        "length": 131,
                        "name": "error",
                        "severity": "ERROR",
                        "code": "22003",
                        "where": "parallel worker",
                        "file": "int8.c",
                        "line": "116",
                        "routine": "scanint8"
                    },
                    "length": 131,
                    "severity": "ERROR",
                    "code": "22003",
                    "where": "parallel worker",
                    "file": "int8.c",
                    "line": "116",
                    "routine": "scanint8",
                    "stacktrace": [
                        "QueryFailedError: value \"10000000000000000000000\" is out of range for type bigint",
                        "    at PostgresQueryRunner.query (/squid/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:211:19)",
                        "    at runMicrotasks (<anonymous>)",
                        "    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
                        "    at async DataSource.query (/squid/node_modules/typeorm/data-source/DataSource.js:341:20)",
                        "    at async EventResolver.lastEvent (/squid/lib/server-extension/resolvers/event.js:33:24)"
                    ]
                }
            }
        }
    ],
    "data": null
}
```

Close issue if it's reported or being solved

**Comment by roiLeo** [comment] 2023-03-17 13:18
might be same fix as #4894

**Comment by yangwao** [comment] 2023-03-17 14:11
related? haven't manage to see which query is it

![image](https://user-images.githubusercontent.com/5887929/225928824-ff75fe52-2593-4ccb-99b9-635c22d82a73.png)

**Comment by daiagi** [comment] 2023-03-18 12:50
it comes from line 58 in ```useCarousel.ts```

```ts
  const { data: dataRmrk2, loading: loadingRmrk2 } = useChainEvents(
    'rmrk2',
    type
  )
```

**Comment by daiagi** [comment] 2023-03-20 07:14
@vikiival  this has been fixed by commit https://github.com/kodadot/rubick/commit/4d91debffc79eb840e1516d8d34ac2ed53f7bf4f
in rubick hasn't it?

need to change url in ```constants.ts``` or something?

**Comment by vikiival** [comment] 2023-03-20 10:10
the problem is that subquery has sort of caching I already redeployed that without any success

**Comment by vikiival** [comment] 2023-03-20 11:30
Made hard reset

```
🦑 Releasing the squid at git@github.com:kodadot/rubick.git#293e682b1be6645abf671e6f307ee741b5668ec5
◷ You may now detach from the build process by pressing Ctrl + C. The Squid deployment will continue uninterrupted.
◷ The new squid will be available as soon as the deployment is complete.
◷ Preparing your squid... ⡿
```

**Comment by daiagi** [comment] 2023-03-20 11:38
:white_check_mark:  wfm

**Closed as completed** 2023-03-20 11:40 UTC
Labels: bug, $, p1, 🧊-indexer
