### ISSUE TITLE
Nuxt - Transaction related problems

### ISSUE THREAD

**Issue by prury** [kodadot/nft-gallery#7403] opened 2023-09-28 14:15 UTC
** = = still testing/editing = =**

<h3> Transfer: </h3>
Tests:

- DOT on Polkadot✔️ 
- DOT on Asset Hub Polkadot ✔️ 
- KSM on Kusama ✔️ 
- KSM on Asset Hub Kusama ✔️ 
- BSX on Basilisk ✔️ 

Problems: 

- [ ] ~~Transfer page Continue button never gets active~~ (Fixed)

<h3> Teleport: </h3>
Tests: 

- Kusama -> KusamaHub ✔️ 
- KusamaHub -> Kusama ✔️ 
- Kusama -> Basilisk ✔️ 
- Basilisk -> Kusama ✔️ 
- Polkadot -> PolkadotHub ✔️ 
- PolkadotHub -> Polkadot ✔️ 

<h3> Drops: </h3>
Problems: 

- [ ] ~~Mint button on Drops not working and if it works it shows a mint failed message~~
- [ ] ~~Ahk mint says its successful, but NFT never really gets created~~
- [ ] ~~Eligibility check not working on Drops~~ (Fixed)
- [x] DOT drop transaction showing error message - fixed by: #7530
- [ ] DOT drop congratulations message appears before approving transaction

<h3> Identity: </h3>

- Identity burning ✔️ 
- ~~identity creation(Kusama) ❌ [Null on every field](https://kusama.subscan.io/tx/0x8408e9c193dc50927be1ff98f9e3f81a7496763a8be1645f8b9576b0879c3faa)~~
- Identity creation ✔️ 

Problems: 
- [x] ~~Not loading identities~~

<h3> NFT Interactions: </h3>
Problems: 

 - [x] Burn on gallery item doesn't trigger transaction
 - [ ] ~~User is able to trigger a NFT creation transaction without selecting a collection~~(Issue Created)
 
 Fixed:
 - [x] ~~On Snek you approve the transaction for NFT creation, it gets approved, but no NFT is created~~
 - [x] ~~List and Transfer NFT not possible as button to confirm never gets active #7479~~ 
 - [x] ~~Create new collection button never triggers transaction (Ahp, Ahk, bsx)~~
 - [x] ~~Create new NFT button never triggers transaction~~
 - [x] ~~Yolo showing on explorer instead of Buy Now~~
 - [x] ~~[Error message](https://github.com/kodadot/nft-gallery/assets/36627808/4573cc74-fc68-4d3d-b6ef-81bbaefcaded) when creating NFT~~
 - [x] ~~Make offer button on Basilisk won't work(insufficient balances)~~

Tests: 
- (RMRK2) Buy: ✔️ 
- (RMRK1) Buy: ✔️ 
- (Ahk) Buy ✔️ 
- (Ahp) Buy ✔️ 
- Cart buy ✔️ 
- Cart many items buy ✔️ 

<h2> Tests V2: </h2>

**AHK** - 
Collection creation ✔️ 
Redirection ❌ 
NFT creation - ✔️ 
redirection - ✔️ 
copies ✔️ 
Properties - not showing

**BSX**
Collection creation - ✔️ 
redirection - ❌ 
NFT creation - ✔️ 
redirection - ✔️ 
copies - ✔️ 
Properties - not showing

**AHP**
Collection creation ✔️ 
redirection - ❌ 
~~NFT creation - [Failing, even if i have 18 dot on Assethub](https://assethub-polkadot.subscan.io/extrinsic/4727475-2)~~ (Works)
redirection - 
copies - 
properties -

**RMRK 2 and 1**
Collection creation - ✔️ 
redirection - ❌ 
NFT creation - ✔️ 
second transaction for listing - ✔️ 
redirection - ✔️ 
copies - ✔️ 
Properties - only showing carbonless 

change price and transfer working across all of them ✔️ 

<h3> Massmint </h3>

 - [ ] After uploading file, UI will not let you go to the second step

**Comment by prury** [comment] 2023-09-28 14:49
cc: @yangwao

**Comment by prury** [comment] 2023-10-03 12:03
> Seems buys works on AHK for me
> 
>     * https://nuxt.kodadot.xyz/ahk/gallery/132-29?listed=true
>       ![image](https://user-images.githubusercontent.com/5887929/272232208-68e85718-020a-4ac5-8c68-689559141914.png)

tyty, will add it to the list and test buy on other chains as well

**Comment by roiLeo** [comment] 2023-10-03 14:13
>     * identity creation(Kusama) ❌ [Null on every field](https://kusama.subscan.io/tx/0x8408e9c193dc50927be1ff98f9e3f81a7496763a8be1645f8b9576b0879c3faa)

It worked for me ([check tx](https://kusama.subscan.io/block/0x779d84ad1d0c426039f399b9a1ffb4006607a884f1d4743e6426e08b89d0d348?tab=extrinsic))
is there a particular way to reproduce it?

**Comment by prury** [comment] 2023-10-03 14:46
> > * identity creation(Kusama) ❌ [Null on every field](https://kusama.subscan.io/tx/0x8408e9c193dc50927be1ff98f9e3f81a7496763a8be1645f8b9576b0879c3faa)
> 
> It worked for me ([check tx](https://kusama.subscan.io/block/0x779d84ad1d0c426039f399b9a1ffb4006607a884f1d4743e6426e08b89d0d348?tab=extrinsic)) is there a particular way to reproduce it?

tried again and it worked, why? haha

**Comment by Jarsen136** [comment] 2023-10-05 03:09
> ### Drops:
> Problems:
> * [ ]  Mint button on Drops not working and if it works it shows a mint failed message

This one should be fixed on `https://nuxt.kodadot.xyz` due to some fix on the graphql request.

**Comment by yangwao** [comment] 2023-10-05 10:36
> * Create new collection button never triggers transaction (Ahp, Ahk, bsx)
> * [ ]  Create new NFT button never triggers transaction

- https://github.com/kodadot/nft-gallery/pull/7502 cc @prury 

Is there anything critical left to be done as to why we should hold on promoting `nuxt` for production?

**Comment by prury** [comment] 2023-10-05 12:56
> > * Create new collection button never triggers transaction (Ahp, Ahk, bsx)
> > * [ ]   Create new NFT button never triggers transaction
> 
>     * [fix: create nft #7502](https://github.com/kodadot/nft-gallery/pull/7502) cc @prury
> 
> 
> Is there anything critical left to be done as to why we should hold on promoting `nuxt` for production?

Will keep looking for problems, as i have been doing. 
Probably nothing critical but i would proceed with caution, i still have to check different media(3d, audio, mp4) nfts and finish checking nft interaction after the recent fixes.

**Comment by prury** [comment] 2023-10-05 13:16
> > * Create new collection button never triggers transaction (Ahp, Ahk, bsx)
> > * [ ]   Create new NFT button never triggers transaction
> 
>     * [fix: create nft #7502](https://github.com/kodadot/nft-gallery/pull/7502) cc @prury
> 

checking rn

**Comment by prury** [comment] 2023-10-05 15:04
@yangwao updated

**Comment by yangwao** [comment] 2023-10-09 09:53
look like good to go? we will discus this week if we should push it for `main` and then make it public following week. 
probably some public bug hunty campaign to see if we missed some bugs

**Comment by prury** [comment] 2023-10-09 12:08
> look like good to go? we will discus this week if we should push it for `main` and then make it public following week. probably some public bug hunty campaign to see if we missed some bugs

only important thing missing its Polkadot AssetHub [nft creation](https://assethub-polkadot.subscan.io/extrinsic/4755577-2)

**Comment by yangwao** [comment] 2023-10-10 16:32
@prury let's create separate issues from outstanding issues and we can close this one 

thank you for making this one!

**Closed** 2023-10-11 13:16 UTC
Labels: $, p1, A-nuxt, chief, hacktoberfest
