### ISSUE TITLE
Rivages: Internal Server Error

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#10977] opened 2024-09-15 17:38 UTC
Collection: https://kodadot.xyz/base/drops/rivages

![image](https://github.com/user-attachments/assets/1f457eb1-4a93-49a9-8e9d-6d41e4b54aa2)

**Comment by vikiival** [comment] 2024-09-16 07:18
Duplicate of https://github.com/kodadot/ops-internal/issues/1909

**Closed by vikiival** 2024-09-16 07:18 UTC
