### ISSUE TITLE
Smaller side margins

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#4857] opened 2023-01-29 11:37 UTC
We should make the margins on fullhd smaller. Its than taking too much space for example in explore. 
![image](https://user-images.githubusercontent.com/90852205/215323213-00342928-5da6-4544-8a97-e3ea09741ac9.png)
something like this everywhere would be good
![image](https://user-images.githubusercontent.com/90852205/215323244-ac2ac02e-8cc3-4ecf-b0c2-d3acae0659ad.png)
is it possible? 

there is set padding to 48px
![image](https://user-images.githubusercontent.com/90852205/215545914-4b394c03-cac9-4cb8-9f85-21b66a28d216.png)
but the content seem to not follow it 

I'm now using a 12 column grid with a 48px margin. On mobile there is 20px margin

**Comment by exezbcz** [comment] 2023-01-30 19:09
would be good to have this after
- #4826

**Comment by exezbcz** [comment] 2023-02-18 12:12
Is there a method to adjust this or does it apply responsively depending on the situation?
<img src="https://media0.giphy.com/media/3oz8xT2mfj0r9YpBwk/giphy.gif"/>

**Comment by roiLeo** [comment] 2023-02-20 07:44
> Is there a method to adjust this or does it apply responsively depending on the situation? 

Idk what you mean by that but we can override [size of container](https://bulma.io/documentation/layout/container/) and set personalized [spacing helpers](https://bulma.io/documentation/helpers/spacing-helpers/)

**Comment by exezbcz** [comment] 2023-02-20 17:17
![Group 227](https://user-images.githubusercontent.com/90852205/220167891-a8fb72e1-3b03-4dc0-acd6-e599bca80b9d.png)

my bad :D 

Yes, I think that is it
- sometimes the margin left right is good but sometimes its taking up too much space on screen

![image](https://user-images.githubusercontent.com/90852205/220167799-504b821b-91e1-4f6d-bfb2-d6183877f0b2.png)

Wdyt?

**Comment by roiLeo** [comment] 2023-02-21 13:29
I can't reproduce container overflowing, could you share what size of screen?
![Capture d’écran 2023-02-21 à 2 26 57 PM](https://user-images.githubusercontent.com/9987732/220357166-faa5e820-865c-41ac-b646-09ac582365f6.png)

Or maybe I'm wrong way, you're waiting for something else? Increase margin on larger screen? Reduce container margin? Reponsive adaptation?

**Comment by exezbcz** [comment] 2023-02-21 17:14
@roiLeo yy, that was not the object of this. 
I am talking about making the side margins of container smaller - context is that I think we should not waste space on explore and stretch the content bit more. 

Lmk if I should clarify something else, sorry for that :D

**Comment by roiLeo** [comment] 2023-04-14 06:43
closed by #5089

**Closed by roiLeo** 2023-04-14 06:43 UTC
Labels: $, p2, visual change
