### ISSUE TITLE
This arrow looks sus

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#5554] opened 2023-04-07 17:09 UTC
Arrow at the end of the infinity scroll in the profile/collection looks kinda messy. Can we center it or was this intentional? 
<img width="351" alt="Screenshot 2023-04-07 at 18 40 12" src="https://user-images.githubusercontent.com/104380776/230648554-cca89f08-2077-4af6-8bab-bed4de5f2fea.png">
<img width="396" alt="Screenshot 2023-04-07 at 19 06 15" src="https://user-images.githubusercontent.com/104380776/230648770-ca856fed-a317-4125-884e-6574d2126a66.png">

**Comment by exezbcz** [comment] 2023-04-07 18:03
duplicate of 
- #5539

**Closed by exezbcz** 2023-04-07 18:03 UTC
Labels: design-request
