### ISSUE TITLE
Echo: Animation not loading properly

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#9431] opened 2024-02-15 15:35 UTC
This NFT does not have animation apparently?? Why?  Shouldn't they all have it? 

This: https://kodadot.xyz/ahp/gallery/95-92

I see same image after 4 minutes of waiting, I tried to refresh.

**Comment by JustLuuuu** [comment] 2024-02-15 15:36
Ok now it works, idk why it was not loading

**Comment by JustLuuuu** [comment] 2024-02-15 15:37
Some animations don't load when you open the NFT:
https://github.com/kodadot/nft-gallery/assets/104380776/2ab54852-5f19-422e-b89d-5731bd6d1ad6

**Comment by prury** [comment] 2024-02-15 15:39
> Some animations don't load when you open the NFT: https://github.com/kodadot/nft-gallery/assets/104380776/2ab54852-5f19-422e-b89d-5731bd6d1ad6

nice catch @JustLuuuu , will not work if you go trough nfts on explorer

**Comment by yangwao** [comment] 2024-02-15 17:46
Rel
-
- https://github.com/kodadot/nft-gallery/issues/9430

**Comment by vikiival** [comment] 2024-02-21 11:53
Also works 
https://github.com/kodadot/nft-gallery/assets/22471030/fff76498-d6c1-4ccb-beac-5564d4e58582

**Comment by vikiival** [comment] 2024-02-21 11:54
Duplicate of #9430

**Closed by vikiival** 2024-02-21 11:54 UTC
Labels: bug, A-generative
