### ISSUE TITLE
Implement Basilisk on-chain identity

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#3481] opened 2022-07-19 09:15 UTC
> & I still see my account name

the account name is quite okayish as it's if an address has set on-chain identity on Kusama. It's the same address on basilisk, and basilisk doesn't offer an identity pallet now, but in the future will, so I bet we can keep it for now against KSM 😄

We can implement an on-chain identity from Basilisk to be independent of KSM in the future.

_Originally posted by @yangwao in https://github.com/kodadot/nft-gallery/issues/3374#issuecomment-1188805087_

**Comment by roiLeo** [comment] 2022-10-27 06:58
Tested on Rococo and it worked! Imo we can close this one

**Comment by roiLeo** [comment] 2023-04-14 06:46
duplicate of #4832? and already working

**Closed by roiLeo** 2023-04-14 06:46 UTC
Labels: research, p5, 🐍 - basilisk
