### ISSUE TITLE
Wrong currency on the landing page

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#6705] opened 2023-08-14 11:46 UTC
There is an issue with the **Polkadot network** on KodaDot. When you open it, it shows prices in DOT (even though the price of NFTs is originally KSM) - the prices are totally wrong. It is happening on the landing page for these two:
- newest list 
- last sales

Same on production and on canary🐦‍⬛

### Reproduce it:
1. Open Kodadot and select Kusama network. Scroll a bit down. Prices are normal:
<img width="1398" alt="Screenshot 2023-08-14 at 13 35 05" src="https://github.com/kodadot/nft-gallery/assets/104380776/3a7bff1c-4fb6-4a32-bc7c-5b9f8b0cb0b3">

2. Change from Kusama to Polkadot. Scroll a bit down. The prices for the same NFTs are shown in DOT (prices do not correspond with the real price of NFTs)
<img width="1375" alt="Screenshot 2023-08-14 at 13 36 18" src="https://github.com/kodadot/nft-gallery/assets/104380776/38587261-5e74-4773-82ca-ffc0ec5d5737">

When you click on any of the NFTs after it opens, the price will jump back to KSM (correct price). It can be a bit confusing.

**Comment by vikiival** [comment] 2023-08-14 13:47
> Change from Kusama to Polkadot. Scroll a bit down. The prices for the same NFTs are shown in DOT (prices do not correspond with the real price of NFTs)


This is caused by using same indexer for both KSM and DOT

So this can be fixed by forbiding landing page on DOT

**Closed** 2023-08-15 08:50 UTC
Labels: bug, A-landing
