### ISSUE TITLE
Animated collection is static

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#10927] opened 2024-09-02 09:38 UTC
Collection: https://kodadot.xyz/base/drops/rvn3

Whole collection should be animated and its static

https://github.com/user-attachments/assets/71c6a094-11eb-4f3f-8372-64f2415ebb0d

**Comment by hassnian** [comment] 2024-09-02 10:04
duplicate of #10875

**Comment by woniuppp** [comment] 2024-09-12 16:10
https://image-beta.w.kodadot.xyz/ipfs/bafybeihaxwqmsusefilvma2x7dick5qiny5izphs2l7l47iysoa5i37fzy/?hash=0x7880aec93413f117ef14bd4e6d130875ab2c7d7d55a064fac3c2f7bd51516380

The picture can be predicted, but the loading of the img tag is blocked.

**Comment by preschian** [comment] 2024-09-13 05:34
this issue and #10875 should be fixed in this PR: https://github.com/kodadot/nft-gallery/pull/10934
the PR will double check to make sure the token get on chain metadata

**Closed** 2024-10-03 10:22 UTC
Labels: bug, p2, A-generative, A-base
