### ISSUE TITLE
Drops Refactor

### ISSUE THREAD

**Issue by daiagi** [kodadot/nft-gallery#9562] opened 2024-02-27 01:16 UTC
Similar to the way we worked on integrating Nuxt3 in a separate branch until all bugs were cleared and then we merged
i propose we do same for drops

### Problem 

I find the drops related code much harder to read and maintain compare to other parts of our app
here are some of the reasons why

1. too many props passed, example: mint button props are being passes `PaidGenerative ->GenerativeLayout -> GenerativePreview -> MintButton and finally into NeoButton`
i don't see a good reason for this pattern. state should be calculated close to where it is used, info can be shared via composables,
like we do elsewhere in the app
2. long long components, probably as side affect of 1, `PaidGenerative` again for example is too long
3. complicated computed props, for example, `PaidGenerative -> mintButtonDisabled` is hard to read
4. function props: this looks like react pattern and not something i've seen elsewhere in the code. like `GenerativeLayout` `props.handleSelectImage`. this should be done via event emit, composable, or if really needed, `Provide/Inject` API

### Call To Action
@kodadot/internal-dev  please feel free to

-  add to the list above
- break this down to smaller tasks and grab them

PR's to [Drops Refactor branch](https://github.com/kodadot/nft-gallery/tree/drops-refactor)

cc @vikiival @yangwao

**Comment by vikiival** [comment] 2024-02-27 01:26
I Agree, i also find it very hard to read and any small change takes me quite a time to find and implement. 

> props drilling

I would not find is as an issue, however lot of code mess comes from Hack it as you go :). 

I expect that any major schema change is not going to happen, so it is a right time to refactor stuff

**Comment by preschian** [comment] 2024-02-27 02:24
> too many props passed

I completely agree with this one. I put the title `"little bit clean up"` in this PR: https://github.com/kodadot/nft-gallery/pull/9534 because I want to raise the same thing about this. Finally, someone feels the same way.

> this should be done via event emit, composable, or if really needed, Provide/Inject API

I agree. We also can use shared state/store 👍🏻
For me, I put `event emit` on the last option (I don't think it is suitable for the props drilling case). But, as long as it can help and does not drill down the props too deep, it is still good to go for me.

refs:
- https://vuejs.org/guide/components/provide-inject
- https://vuejs.org/guide/reusability/composables.html#composables
- https://nuxt.com/docs/getting-started/state-management

**Comment by daiagi** [comment] 2024-02-27 02:33
>I put event emit on the last option

sure, i didn't list it on order of preference
anything to get us out of this props drill mess in a nice, readable, clear maintainable way is good

shared store with maybe some util composables on top will probably work nicely

**Comment by daiagi** [comment] 2024-02-27 02:47
Tasks:

- [ ] Unify minting across variations ([ref](https://github.com/kodadot/nft-gallery/issues/9563#issuecomment-1965686037))

**Comment by vikiival** [comment] 2024-02-28 20:03
Closing for the sake of #9575

Duplicate of #9575

**Closed as not planned by vikiival** 2024-02-28 20:03 UTC
Labels: intern, A-refactoring, A-drop-page
