### ISSUE TITLE
Mint nft button disabled and enabled states 

### ISSUE THREAD

**Issue by exezbcz** [kodadot/nft-gallery#8103] opened 2023-11-16 16:45 UTC
It seems like its not working 100% 
- I opened the drop page, and the button was disabled even though I hadn't minted yet. This could be a cookie issue, but still worth fixing because I am not the only one that minted the previous drop 
- I reconnected a different wallet, minted nft and the button is still enabled - should be disabled state

<img width="1470" alt="image" src="https://github.com/kodadot/nft-gallery/assets/90852205/4aea9e27-f8c6-4a44-93f4-3abe87a65804">

![image](https://github.com/kodadot/nft-gallery/assets/90852205/2b0fade8-eb91-4fa3-b21f-a355448c0102)

**Comment by yangwao** [comment] 2023-11-16 17:03
happened to me as well not sure if the glitch couldn't replicate

**Comment by yangwao** [comment] 2023-11-16 17:07
https://twitter.com/JegorSidorenko/status/1725177703194636674

**Comment by exezbcz** [comment] 2023-11-16 17:52
on my address it does not work

![image](https://github.com/kodadot/nft-gallery/assets/90852205/f1e9fe7c-dffb-40ad-990c-307b89a74120)


![image](https://github.com/kodadot/nft-gallery/assets/90852205/2ce6e455-3523-4bfa-9917-1e1965b932c2)
- I have nothing on my profile but cannot mint

address: 1cQB9WUTtwyH3H4Ksn7pLfJvMLCxtzQHbUNhZtVBasoX3X9

**Comment by yangwao** [comment] 2023-11-23 12:18
might be fixed in 
- #8208

**Comment by exezbcz** [comment] 2023-11-23 12:18
@yangwao we are on the same page

**Comment by yangwao** [comment] 2023-11-23 12:19
> page

<img src="https://media3.giphy.com/media/3o6MbiSEwjDotYxJ2U/giphy.gif"/>

**Comment by exezbcz** [comment] 2023-11-25 10:25
we really have to make this bulletproof for upcoming airdrops

rel: 
- #8163

**Comment by Jarsen136** [comment] 2023-11-29 17:01
> It seems like its not working 100%
> 
> * I opened the drop page, and the button was disabled even though I hadn't minted yet. This could be a cookie issue, but still worth fixing because I am not the only one that minted the previous drop

The button is disabled at the beginning because the drop has not started yet.


> * I reconnected a different wallet, minted nft and the button is still enabled - should be disabled state
> 
It should be fixed by #8288

**Comment by exezbcz** [comment] 2023-11-29 17:13
> I guess the button is disabled at the beginning because the drop has not started yet.
> 
> >

It's the previous drop, I was testing it when it was live. Similar issues were reported by other users when for example the swirls drop was live

**Comment by Jarsen136** [comment] 2023-11-30 06:27
> > I guess the button is disabled at the beginning because the drop has not started yet.
> > >
> 
> It's the previous drop, I was testing it when it was live. Similar issues were reported by other users when for example the swirls drop was live

I'll keep an eye out to see if I can reproduce this problem.

**Closed** 2023-12-04 19:36 UTC
Labels: $, p1, A-drop-page
