### ISSUE TITLE
Uncaught Error: Expected a valid key to convert, with length 1, 2, 4, 8, 32, 33

### ISSUE THREAD

**Issue by ltfschoen** [kodadot/nft-gallery#9412] opened 2024-02-15 08:57 UTC
### Is there an existing issue?

- [X] I have searched the existing issues

### What happened?

Go to kodadot.xyz, click to connect Polkadot.js Extension and it shows that error in latest Brave browser

### Please reproduce in steps

Click "Connect" > "Polkadot.js", then view browser console error

### Expected Behavior

It should allow me to connect Polkadot.js Extension on a desktop browser if I want to. I shouldn't be forced to use other wallets.

Previously I encountered and reported this error on https://singular.app/ but it has now been fixed there, but there is an error at https://kodadot.xyz

### Solution

The solution is explained here https://github.com/polkadot-js/extension/issues/1250#issuecomment-1931926244. Credit to the Subsocial team for quickly resolving the solution after I posted the issue here https://polkaverse.com/@luke/polkadot-d-app-errors-when-handling-accounts-supplied-by-the-47114. Since then Zeitgeist fixed the issue too in their codebase here too https://github.com/zeitgeistpm/ui/issues/2185#event-11773056586

### What browsers are you seeing the problem on?

Other

### At which address did you encounter bug?

kodadot.xyz

### Are you logged in?

No

### Which wallet you are using?

PolkadotJS

### At which chain did you encounter bug?

Asset Hub Polkadot

### Screenshots

<img width="566" alt="Screenshot 2024-02-15 at 7 34 27 pm" src="https://github.com/kodadot/nft-gallery/assets/6226175/82b4849c-0a1c-4d0d-b410-f985b04d46b1">

### Payment link for reward

https://canary.kodadot.xyz/dot/transfer/?target=1dsrQjL34njJ4Y8FXGyxeLnmunPZ6XAvid9jSQe9S4pTUh2

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yangwao** [comment] 2024-02-15 09:48
Does it happen outside Brave?

**Comment by ltfschoen** [comment] 2024-02-15 10:44
I don't get the error using Firefox

**Comment by ltfschoen** [comment] 2024-02-15 10:44
> Does it happen outside Brave?

I don't get the error using Firefox

**Comment by iMac7** [comment] 2024-02-23 06:27
@ltfschoen works on my end. Is this still an issue? What's your browser version :thinking:

**Comment by ltfschoen** [comment] 2024-02-23 06:31
Could it be be similar to this issue if I'm using other extensions https://github.com/AcalaNetwork/Acala/issues/2710#issuecomment-1958588449

**Comment by iMac7** [comment] 2024-02-23 06:48
> Could it be be similar to this issue if I'm using other extensions [AcalaNetwork/Acala#2710 (comment)](https://github.com/AcalaNetwork/Acala/issues/2710#issuecomment-1958588449)

Yep looks similar.
I use amd64 on debian and I'm not sure if my brave is the latest version. What's your system and brave version so I can replicate the issue?

**Comment by ltfschoen** [comment] 2024-02-23 07:15
tried both of these versions, same error:
Brave: Version 1.62.165 Chromium: 121.0.6167.184 (Official Build) (arm64)
Brave: Version 1.63.161 Chromium: 122.0.6261.57 (Official Build) (arm64)
macOS 14.1.1 (23B81)

**Comment by iMac7** [comment] 2024-02-23 09:41
> Brave: Version 1.62.165 Chromium: 121.0.6167.184 (Official Build) (arm64)
> Brave: Version 1.63.161 Chromium: 122.0.6261.57 (Official Build) (arm64) - LATEST
> macOS 14.1.1 (23B81)

Can't reproduce on my end, maybe it's not on amd64/linux. Tried on brave 1.61, 1.62 and 1.63

**Comment by hassnian** [comment] 2024-11-16 04:51
Closed by #10550

**Closed by hassnian** 2024-11-16 04:51 UTC
Labels: bug, $, p3
