### ISSUE TITLE
Grayscale & Monochrome option

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1370] opened 2021-12-02 09:14 UTC
Let's see if we can add attribute monochrome and greyscale nfts and then we can filter them out.

Could be also made as plugin to drive greyscale/monochrome lenses over all NFTs 

# ref 
- https://en.wikipedia.org/wiki/Grayscale
- https://en.wikipedia.org/wiki/Monochrome

**Comment by vikiival** [comment] 2021-12-02 09:56
<img width="1125" alt="Screenshot 2021-12-02 at 10 55 40" src="https://user-images.githubusercontent.com/22471030/144399336-0d341932-65c8-4c69-8b56-ee6705018d06.png">


```css
body {
    filter: grayscale(1);
}
```

**Comment by yangwao** [comment] 2021-12-02 12:25
Can we put it into options/settings #1308 #942

**Comment by vikiival** [comment] 2022-01-07 15:37
https://color-mode.nuxtjs.org

**Comment by yangwao** [comment] 2022-01-13 18:32
We need Berlin color palette
https://twitter.com/AuslanderMemes/status/1481181559189385216?t=_V1Qa_HxjWsv2OylhM7pLQ&s=09

**Comment by vikiival** [comment] 2024-07-31 13:07
Duplicate of #1372 

- https://github.com/kodadot/nft-gallery/issues/1372#issuecomment-2260329738

**Comment by vikiival** [comment] 2024-07-31 13:07
- https://github.com/kodadot/nft-gallery/issues/1372#issuecomment-2260329738

**Closed by vikiival** 2024-07-31 13:07 UTC
Labels: $, A-research, p3, A-nuxt, v2.2
