### ISSUE TITLE
Implement ink! nft marketplace into KodaDot 

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#3084] opened 2022-05-29 13:58 UTC
This is a pure research stage issue

- https://github.com/gear-tech/apps/tree/master/nft-marketplace
- https://github.com/gear-tech/apps/tree/master/nft-marketplace/nft

**Comment by roiLeo** [comment] 2023-05-24 07:12
Apply for ink! Grant => https://github.com/use-inkubator/Ecosystem-Grants

**Comment by vikiival** [comment] 2024-07-31 11:19
Duplicate of - https://github.com/kodadot/ops-internal/issues/292

**Closed by vikiival** 2024-07-31 11:19 UTC
Labels: A-research, p4, A-astar, A-gear-tech, A-aleph-zero
