### ISSUE TITLE
arts (mp4) are not displayed after uploading

### ISSUE THREAD

**Issue by dv2ku** [kodadot/nft-gallery#8815] opened 2023-12-30 16:22 UTC
### What happened?

arts (mp4) are not displayed after uploading. one nft still don`t have preview 
![photo_2023-12-30_19-14-55](https://github.com/kodadot/nft-gallery/assets/155249919/f5bac1af-c765-4ba8-8f90-ab2dd20e30e2)
![photo_2023-12-30_19-14-57](https://github.com/kodadot/nft-gallery/assets/155249919/46328bee-92e6-487c-84af-fd445fe57fa1)
Collection:
https://kodadot.xyz/ahk/collection/329

### Please reproduce in steps

1. mp4 files are not played as videos or gif
2. one nft don`t have preview 

### Expected Behavior

the files should be displayed as gif, also all of them should have previews 

### What browsers are you seeing the problem on?

Chrome, Mobile iOS Safari

### Are you logged in?

Yes

### Which wallet you are using?

PolkadotJS

### Screenshots

![photo_2023-12-30_19-14-55](https://github.com/kodadot/nft-gallery/assets/155249919/73d2f949-318a-4d6a-ba59-a738c624f7e0)
![photo_2023-12-30_19-14-57](https://github.com/kodadot/nft-gallery/assets/155249919/f0ed6ba8-545c-4e99-8da2-940e2d3410dd)

### Wallet Address & Transaction hash

Cz8noz4k5BnNsCN9uy2ZaBLhM1Ytk2psng6Lz1sKzwj37im

### Payment link for reward

https://canary.kodadot.xyz/dot/transfer/?target=<My_Polkadot_Address_check_https://github.com/kodadot/nft-gallery/blob/main/REWARDS.md#creating-your-dot-address>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hassnian** [comment] 2024-01-01 07:17
duplicate of #8641

fixed here #8729 

![CleanShot 2024-01-01 at 12 14 25](https://github.com/kodadot/nft-gallery/assets/44554284/041c7cae-675f-45e5-aeab-078d8f043f30)

**Comment by roiLeo** [comment] 2024-01-02 08:59
continue #8805

**Closed by roiLeo** 2024-01-02 08:59 UTC
Labels: bug, p2, A-statemint-ahp

**Comment by dv2ku** [comment] 2024-01-02 09:22
![11](https://github.com/kodadot/nft-gallery/assets/155249919/8140665e-7b77-421f-87a9-557405ef9341)
![12](https://github.com/kodadot/nft-gallery/assets/155249919/a8115d13-fde4-4def-bd32-6de6777d2938)
gm, thank you

nft "the eye of eternel" still not have preview for ios and chrome
also price on all nfts are 0

**Comment by hassnian** [comment] 2024-01-02 09:39
> preview issue fixed here #8729

pls wait for this pr to be merged , that issue 

> nft "the eye of eternel" still not have preview for ios and chrome

should be fixed
