### ISSUE TITLE
drunk corners

### ISSUE THREAD

**Issue by ins0mn1a** [kodadot/nft-gallery#756] opened 2021-09-20 20:23 UTC
While hovering with mouse over NFT in gallery, corners going from round to straight.

1. https://kodadot.xyz/rmrk/gallery
2. Hover mouse over any NFT ( best is it visible with zoom )

<img width="420" alt="Screen Shot 2021-09-20 at 22 21 39" src="https://user-images.githubusercontent.com/10535692/134070190-3865bbee-7657-4368-ad0d-405a6a61a912.png">

**Comment by roiLeo** [comment] 2021-09-21 06:25
Could you give us more details about this tipsy border? it seems that I can't reproduce it.

**Comment by vikiival** [comment] 2021-09-21 06:32
@roiLeo It happens only on cards in the collection detail
https://kodadot.xyz/rmrk/collection/20bdacc2872f706827-KYGEVEREST

**Comment by yangwao** [comment] 2021-09-21 07:19
Maybe can be mitigated right away by upgrading to motion cards  #745

**Comment by roiLeo** [comment] 2021-12-29 10:43
closing this as it seems to be fixed, feel free to reopen it if you encounter the bug again

**Closed by roiLeo** 2021-12-29 10:43 UTC
Labels: bug, p3
