### ISSUE TITLE
All Base generative drops showing as pictures in collection view

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#10803] opened 2024-08-13 10:48 UTC
Open any Base collection. For example this one: https://kodadot.xyz/base/collection/0xe215f77d95b83a098da0dfcb93af901fe6524dfe

All of them have that "picture" in the corner

<img width="1028" alt="Screenshot 2024-08-13 at 12 45 06" src="https://github.com/user-attachments/assets/cb270ce3-407a-4749-93ef-c7e888f3f74a">

<img width="1216" alt="Screenshot 2024-08-13 at 12 47 33" src="https://github.com/user-attachments/assets/9da4a9ac-1f02-47fb-ab80-65d4b6aeef21">

**Comment by roiLeo** [comment] 2024-08-15 11:43
duplicate of #10736?

**Comment by JustLuuuu** [comment] 2024-08-15 11:45
yeah duplicatw, but still needs to be solved

**Closed** 2024-08-15 11:45 UTC
Labels: bug, p2, A-collection, A-base
