### ISSUE TITLE
Hide items on user profile

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#442] opened 2021-06-09 09:33 UTC
Whenever someone send you item you don't want to be listed on profile 
https://twitter.com/insider0x/status/1402373401851858945

Opensea introduced it as well
https://twitter.com/opensea/status/1402253451585859585

**Comment by ed-iv** [comment] 2021-06-09 20:12
Another use-case is hiding stuff that you've burned. I inadvertently minted a bunch of duplicates due to issues caused by kanaria emote scripts that were subsequently burned in addition to some test mints which I'd like to hide.

**Comment by yangwao** [comment] 2021-06-10 12:07
> Another use-case is hiding stuff that you've burned. I inadvertently minted a bunch of duplicates due to issues caused by kanaria emote scripts that were subsequently burned in addition to some test mints which I'd like to hide.

Okay, options came to my thought. Let me know what do you think
Hide by 
- [ ] address of sender
- [ ] by selected NFT

**Comment by yangwao** [comment] 2021-06-23 14:56
- [ ] Hide burned NFTs

**Comment by vikiival** [comment] 2021-06-23 15:39
OK looks like we have a small glitch in subquery

```graphql
query notBurned {
  nFTEntities(filter: { burned: {equalTo: false }  }) {
    nodes {
      burned
    }
  }
}
```

It returns empty

**Comment by yangwao** [comment] 2021-09-21 07:40
We've hide #679 already, but specifically, hide NFT is still a good thing to have. 
One way is the user can now burn it, but maybe need to keep it as an access token?

**Comment by vikiival** [comment] 2021-10-20 11:31
Yup, legit for now!

**Comment by vikiival** [comment] 2021-12-02 16:56
Closing in favour of #1367

**Closed** 2021-12-02 16:56 UTC
Labels: enhancement, $, p4
